
import React from 'react';
import { X, Zap, Settings, Play } from 'lucide-react';

export interface UserSettings {
  autoExecute: boolean;
}

interface Props {
  isOpen: boolean;
  onClose: () => void;
  settings: UserSettings;
  onUpdate: (key: keyof UserSettings, value: boolean) => void;
}

const SettingsModal: React.FC<Props> = ({ isOpen, onClose, settings, onUpdate }) => {
  if (!isOpen) return null;

  return (
    <div className="fixed inset-0 z-[200] flex items-center justify-center p-4">
      <div className="absolute inset-0 bg-black/40 backdrop-blur-sm" onClick={onClose}></div>
      <div className="bg-white rounded-2xl shadow-2xl w-full max-w-md relative overflow-hidden animate-in fade-in zoom-in-95 duration-200">
        <div className="px-6 py-4 border-b border-gray-100 flex items-center justify-between bg-gray-50/50">
          <h3 className="text-lg font-black text-gray-900 flex items-center gap-2">
            <Settings size={20} className="text-gray-400" />
            Global Configuration
          </h3>
          <button onClick={onClose} className="p-2 hover:bg-gray-200 rounded-full text-gray-400 transition-colors">
            <X size={20} />
          </button>
        </div>
        
        <div className="p-6 space-y-6">
          <div className="flex items-center justify-between group p-3 -mx-3 hover:bg-gray-50 rounded-xl transition-colors">
            <div className="space-y-1.5">
              <div className="flex items-center gap-2">
                 <div className={`p-1.5 rounded-lg ${settings.autoExecute ? 'bg-green-100 text-green-600' : 'bg-gray-100 text-gray-400'}`}>
                    <Play size={14} fill={settings.autoExecute ? "currentColor" : "none"} />
                 </div>
                 <h4 className="text-sm font-bold text-gray-800">Auto-Run Generated Code</h4>
              </div>
              <p className="text-xs text-gray-500 max-w-[260px] leading-relaxed font-medium">
                When enabled, SQL queries and Python scripts generated by AI will be executed automatically.
              </p>
            </div>
            <label className="relative inline-flex items-center cursor-pointer">
              <input 
                type="checkbox" 
                checked={settings.autoExecute}
                onChange={(e) => onUpdate('autoExecute', e.target.checked)}
                className="sr-only peer" 
              />
              <div className="w-11 h-6 bg-gray-200 peer-focus:outline-none rounded-full peer peer-checked:after:translate-x-full peer-checked:after:border-white after:content-[''] after:absolute after:top-[2px] after:left-[2px] after:bg-white after:border-gray-300 after:border after:rounded-full after:h-5 after:w-5 after:transition-all peer-checked:bg-green-500"></div>
            </label>
          </div>
        </div>
        
        <div className="px-6 py-4 bg-gray-50 border-t border-gray-100 text-[10px] text-gray-400 font-bold uppercase tracking-widest text-center">
            Settings persisted for User ID: 0
        </div>
      </div>
    </div>
  );
};

export default SettingsModal;
